apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: altinity-operator
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: altinity-clickhouse-operator
    repoURL: https://altinity.github.io/clickhouse-operator
    targetRevision: 0.23.6
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
