apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clickhouse
  namespace: argocd
  annotations: 
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    namespace: clickhouse
    server: https://kubernetes.default.svc
  project: default
  source:
    path: clickhouse
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
