apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clickhouse-cluster 
  namespace: argocd
  annotations: 
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: default
  sources:
    - chart: clickhouse-eks
      repoURL: https://altinity.github.io/kubernetes-blueprints-for-clickhouse
      targetRevision: 0.1.2
      helm:
        valueFiles:
          - $values/argo-apps/values/keeper-cluster.yaml
    - repoURL: 'https://github.com/joshleecreates/clickhouse-opentelemetry-iac.git'
      targetRevision: main
      ref: values
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
