apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clickhouse-operator 
  namespace: argocd
  annotations: 
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: default
  sources:
    - chart: clickhouse-operator
      repoURL: https://docs.altinity.com/clickhouse-operator/
      targetRevision: release-0.23.6
      helm:
        valueFiles:
          - $values/argo-apps/values/clickhouse.yaml
    - repoURL: 'https://github.com/joshleecreates/clickhouse-opentelemetry-iac.git'
      targetRevision: main
      ref: values
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
