apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clickhouse-operator 
  namespace: argocd
  annotations: 
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: default
  sources:
    - chart: altinity-clickhouse-operator
      repoURL: https://altinity.github.io/clickhouse-operator
      targetRevision: 0.23.6
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
