apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keeper-sts
  namespace: argocd
  annotations: 
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    namespace: clickhouse
    server: https://kubernetes.default.svc
  project: default
  sources:
    - chart: keeper-sts
      repoURL: https://altinity.github.io/kubernetes-blueprints-for-clickhouse
      targetRevision: 0.1.1
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
