image:
  repository: "otel/opentelemetry-collector-contrib"
enabled: true
mode: deployment
presets:
  kubernetesAttributes:
    enabled: true
service:
  type: ClusterIP
ports:
  metrics:
    enabled: true
  prometheus:
    enabled: true
    containerPort: 9464
    servicePort: 9464
    protocol: TCP
