apiVersion: v2
name: clickhouse
description: Deploys a ClickHouse Cluster with the Altinity Operator
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
- name: opentelemetry-collector
  version: "0.106.1"
  repository: https://open-telemetry.github.io/opentelemetry-helm-charts/
- name: grafana
  version: "8.4.0"
  repository: https://grafana.github.io/helm-charts
