####################################################
#### ClickHouse ####################################
####################################################

# clickhouse-eks:
#   all:
#     metadata:
#       labels:
#         application_group: monitoring
#
#   clickhouse:
#     name: clickhouse
#     cluster: monitoring 
#     zones:
#       - us-west-2a
#       - us-west-2b
#       - us-west-2c
#     node_selector: "m6i.large"
#     service_type: "ClusterIP"
#     storage_class_name: gp3-encrypted
#     keeper_name: keeper-keeper
#
  
####################################################
#### OpenTelemetry Collector #######################
####################################################
opentelemetry-collector:
  image:
    repository: otel/opentelemetry-collector-contrib

  mode: daemonset

  presets:
    # enables the k8sattributesprocessor and adds it to the traces, metrics, and logs pipelines
    kubernetesAttributes:
      enabled: true
    # enables the kubeletstatsreceiver and adds it to the metrics pipelines
    kubeletMetrics:
      enabled: true
    # Enables the filelogreceiver and adds it to the logs pipelines
    logsCollection:
      enabled: true

  extraEnvs:
    # - name: CLICKHOUSE_USERNAME
    #   valueFrom:
    #     secretKeyRef:
    #       name: clickhouse-credentials
    #       key: user
    # - name: CLICKHOUSE_PASSWORD
    #   valueFrom:
    #     secretKeyRef:
    #       name: clickhouse-credentials
    #       key: password
  config:
    exporters:
      clickhouse:
        endpoint: clickhouse://clickhouse-monitoringdb:9000?dial_timeout=10s&compress=lz4
        database: otel
        # username: '${env:CLICKHOUSE_USERNAME}'
        # password: '${env:CLICKHOUSE_PASSWORD}'
        username: collector
        password: collector
        create_schema: true
        logs_table_name: otel_logs
        traces_table_name: otel_traces
        metrics_table_name: otel_metrics
        timeout: 5s
        # cluster_name: dev
        retry_on_failure:
          enabled: true
          initial_interval: 5s
          max_interval: 30s
          max_elapsed_time: 300s
    service:
      pipelines:
        logs:
          exporters: [clickhouse]


####################################################
#### Grafana #######################################
####################################################
grafana:
  grafana.ini:
    auth:
      disable_login_form: true
    auth.anonymous:
      enabled: true
      org_name: Main Org.
      org_role: Admin
    server:
      root_url: "%(protocol)s://%(domain)s:%(http_port)s/"
  adminPassword: admin
  # persistence:
  #   type: pvc
  #   enabled: true
  #   size: 5Gi
  plugins:
    - grafana-clickhouse-datasource
    - vertamedia-clickhouse-datasource
