####################################################
# OpenTelemetry Collector
####################################################
opentelemetry-collector:
  image:
    repository: otel/opentelemetry-collector-contrib

  mode: daemonset

  presets:
    # enables the k8sattributesprocessor and adds it to the traces, metrics, and logs pipelines
    kubernetesAttributes:
      enabled: true
    # enables the kubeletstatsreceiver and adds it to the metrics pipelines
    # kubeletMetrics:
    #   enabled: true
    # Enables the filelogreceiver and adds it to the logs pipelines
    logsCollection:
      enabled: true
      includeCollectorLogs: true

  extraEnvs:
    # - name: CLICKHOUSE_USERNAME
    #   valueFrom:
    #     secretKeyRef:
    #       name: clickhouse-credentials
    #       key: user
    # - name: CLICKHOUSE_PASSWORD
    #   valueFrom:
    #     secretKeyRef:
    #       name: clickhouse-credentials
    #       key: password
  config:
    receivers:
      kubeletstats:
        auth_type: "none"
      filelog:
        operators:
          # Route based on whether the log is JSON or plain text
          - type: router
            id: log_type_router
            field: body  # Assuming logs are in the 'body' field
            routes:
              - value: '{'
                output: json_route
              - value: "^[A-Z]"  # Starts with a log level prefix
                output: text_route

          # Route for JSON formatted logs
          - id: json_route
            type: json_parser
            parse_from: body

          # Handle SeverityNumber and SeverityText for JSON logs (if present)
          - type: router
            id: json_severity_router
            field: level
            routes:
              - value: "INFO"
                output: 9
              - value: "WARN"
                output: 13
              - value: "ERROR"
                output: 17
              - value: "FATAL"
                output: 21

          # Route for plain text logs with the log level prefix
          - id: text_route
            type: regex_parser
            regex: '^(?P<log_level>[IWEF])(?P<date>\d{4}) (?P<time>\d{2}:\d{2}:\d{2}\.\d{6}) (?P<process_id>\d+) (?P<file>[^]]+)\] (?P<log>.*)$'

          # Move the log level into a 'severity' field
          - type: move
            from: log_level
            to: severity
            include: text_route

          # Convert the log level to the appropriate severity text
          - type: router
            id: severity_router
            field: severity
            routes:
              - value: "I"
                output: "INFO"
              - value: "W"
                output: "WARN"
              - value: "E"
                output: "ERROR"
              - value: "F"
                output: "FATAL"
            include: text_route

          # Clean up the prefix for text logs
          - type: regex
            regex: '^[A-Z]\d{4} \d{2}:\d{2}:\d{2}\.\d{6} \d+ [^]]+\] '
            expr: log
            replace: ''
            include: text_route
    exporters:
      clickhouse:
        endpoint: clickhouse://clickhouse-monitoringdb:9000?dial_timeout=10s&compress=lz4
        database: otel
        # username: '${env:CLICKHOUSE_USERNAME}'
        # password: '${env:CLICKHOUSE_PASSWORD}'
        username: collector
        password: collector
        create_schema: true
        logs_table_name: otel_logs
        traces_table_name: otel_traces
        metrics_table_name: otel_metrics
        timeout: 5s
        # cluster_name: dev
        retry_on_failure:
          enabled: true
          initial_interval: 5s
          max_interval: 30s
          max_elapsed_time: 300s
    service:
      pipelines:
        logs:
          exporters: [debug, clickhouse]
        metrics:
          exporters: [debug, clickhouse]
        traces:
          exporters: [debug, clickhouse]

####################################################
# Grafana
####################################################
grafana:
  grafana.ini:
    auth:
      disable_login_form: true
    auth.anonymous:
      enabled: true
      org_name: Main Org.
      org_role: Admin
    server:
      root_url: "%(protocol)s://%(domain)s:%(http_port)s/"
  adminPassword: admin
  # persistence:
  #   type: pvc
  #   enabled: true
  #   size: 5Gi
  plugins:
    - grafana-clickhouse-datasource
    - vertamedia-clickhouse-datasource
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: 'default'
          orgId: 1
          folder: ''
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /var/lib/grafana/dashboards/default
  dashboardsConfigMaps:
    default: chmonitoring-grafana-dashboards
  # dashboards:
  #   default:
  #     cluster-logs:
  #       file: dashboards/cluster-logs.json
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
      - name: ClickHouse-Grafana
        uid: clusterclickhouse
        type: grafana-clickhouse-datasource
        jsonData:
          defaultDatabase: otel
          port: 9000
          host: clickhouse-monitoringdb
          username: 'grafana'
          tlsSkipVerify: true
          logs:
            otelEnabled: true
            defaultDatabase: otel
            defaultTable: otel_logs
          traces:
            otelEnabled: true
            defaultDatabase: otel
            defaultTable: otel_traces
        secureJsonData:
          password: 'grafana'
      - name: ClickHouse-Altinity
        uid: clickhouse-altinity
        editable: true
        access: proxy
        type: vertamedia-clickhouse-datasource
        url: http://clickhouse-monitoringdb:8123
        jsonData:
          defaultDatabase: otel
          addCorsHeader: true
          serverName: "clickhouse"
          usePOST: true
          useYandexCloudAuthorization: true
          xHeaderUser: 'grafana'
          tlsSkipVerify: true
          dataSourceUrl: http://clickhouse-monitoringdb:8123
        secureJsonData:
          xHeaderKey: 'grafana'
