####################################################
# OpenTelemetry Collector
####################################################
opentelemetry-collector:
  image:
    repository: otel/opentelemetry-collector-contrib

  mode: daemonset

  presets:
    # enables the k8sattributesprocessor and adds it to the traces, metrics, and logs pipelines
    kubernetesAttributes:
      enabled: true
    # enables the kubeletstatsreceiver and adds it to the metrics pipelines
    # kubeletMetrics:
    #   enabled: true
    # Enables the filelogreceiver and adds it to the logs pipelines
    logsCollection:
      enabled: true
      includeCollectorLogs: true

  config:
    receivers:
      kubeletstats:
        auth_type: "none"
      filelog:
        operators:
          # Route based on whether the log is JSON or plain text
          - type: router
            id: log_type_router
            field: body  # Assuming logs are in the 'body' field
            routes:
              - expr: 'body matches "^\\{"'
                output: json_route
              - expr: 'true'
                output: regex_route
          # Route for JSON formatted logs
          - id: json_route
            type: json_parser
            parse_from: body
          - id: regex_route
            type: regex_parser
            regex: '(?P<timestamp>\d{4}\.\d{2}\.\d{2} \d{2}:\d{2}:\d{2}\.\d{6}) \[ (?P<thread_id>\d+) \] \{(?P<query_id>[a-f0-9-]+)\} <(?P<log_level>\w+)> (?P<component>\w+): (?P<message>.+)'
            timestamp:
              layout: '%Y.%m.%d %H:%M:%S.%f'
            resource_attributes:
              - key: log.thread_id
                from: thread_id
              - key: log.query_id
                from: query_id
              - key: log.level
                from: log_level
              - key: log.component
                from: component
              - key: log.message
                from: message
    exporters:
      clickhouse:
        endpoint: clickhouse://clickhouse-monitoringdb:9000?dial_timeout=10s&compress=lz4
        database: otel
        username: collector
        password: collector
        create_schema: true
        logs_table_name: otel_logs
        traces_table_name: otel_traces
        metrics_table_name: otel_metrics
        timeout: 5s
        retry_on_failure:
          enabled: true
          initial_interval: 5s
          max_interval: 30s
          max_elapsed_time: 300s
    service:
      pipelines:
        logs:
          receivers: [filelog]
          processors: []
          exporters: [clickhouse]
        metrics:
          receivers: [kubeletstats]
          processors: []
          exporters: [clickhouse]

####################################################
# Grafana
####################################################
grafana:
  grafana.ini:
    auth:
      disable_login_form: true
    auth.anonymous:
      enabled: true
      org_name: Main Org.
      org_role: Admin
    server:
      root_url: "%(protocol)s://%(domain)s:%(http_port)s/"
  adminPassword: admin
  # persistence:
  #   type: pvc
  #   enabled: true
  #   size: 5Gi
  plugins:
    - grafana-clickhouse-datasource
    - vertamedia-clickhouse-datasource
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: 'default'
          orgId: 1
          folder: ''
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /var/lib/grafana/dashboards/default
  dashboardsConfigMaps:
    default: chmonitoring-grafana-dashboards
  # dashboards:
  #   default:
  #     cluster-logs:
  #       file: dashboards/cluster-logs.json
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
      - name: ClickHouse-Grafana
        uid: clusterclickhouse
        type: grafana-clickhouse-datasource
        jsonData:
          defaultDatabase: otel
          port: 9000
          host: clickhouse-monitoringdb
          username: 'grafana'
          tlsSkipVerify: true
          logs:
            otelEnabled: true
            defaultDatabase: otel
            defaultTable: otel_logs
          traces:
            otelEnabled: true
            defaultDatabase: otel
            defaultTable: otel_traces
        secureJsonData:
          password: 'grafana'
      - name: ClickHouse-Altinity
        uid: clickhouse-altinity
        editable: true
        access: proxy
        type: vertamedia-clickhouse-datasource
        url: http://clickhouse-monitoringdb:8123
        jsonData:
          defaultDatabase: otel
          addCorsHeader: true
          serverName: "clickhouse"
          usePOST: true
          useYandexCloudAuthorization: true
          xHeaderUser: 'grafana'
          tlsSkipVerify: true
          dataSourceUrl: http://clickhouse-monitoringdb:8123
        secureJsonData:
          xHeaderKey: 'grafana'
