# ClickHouse using default storage class.
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "monitoringdb"
  labels:
    application_group: "monitoring"
spec:
  configuration:
    users:
      collector/networks/ip: 10.0.0.0/8
      collector/password: collector
      collector/profile: default
      grafana/networks/ip: 10.0.0.0/8
      grafana/password: grafana
      grafana/profile: readonly
    profiles:
      readonly/readonly: 1
    clusters:
      - name: "monitoring"
    
