# ClickHouse using default storage class.
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "monitoringdb"
  labels:
    application_group: "monitoring"
spec:
  configuration:
    clusters:
      - name: "monitoring"
